[tool.poetry]
name = "postcactus"
version = "3.0.0a10"
description = "Read and analyze Einstein Toolkit simulations."
authors = ["Gabriele Bozzola <gabrielebozzola@arizona.edu>"]
maintainers = ["Gabriele Bozzola <gabrielebozzola@arizona.edu>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/sbozzolo/PostCactus"
repository = "https://github.com/sbozzolo/PostCactus"
documentation = "https://sbozzolo.github.io/PostCactus"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sbozzolo/PostCactus/issues"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18.5"
scipy = "^1.5.2"
h5py = "^2.10.0"
numba = "^0.51.2"
matplotlib = "^3.3.2"
ConfigArgParse = "^1.2.3"

[tool.poetry.dev-dependencies]
lalsuite = "^6.77"
black = "^20.8b1"
coverage = "^5.3"
pycbc = "^1.16.10"
Sphinx = "^3.2.1"
nbsphinx = "^0.7.1"
jupyter = "^1.0.0"
mayavi = "^4.7.2"
tikzplotlib = "^0.9.6"
snakeviz = "^2.1.0"

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | docs
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

